### ISSUE TITLE
[Feature Request] Log to stderr

### ISSUE THREAD

**Issue by halorrr** [mastiffmushroom/TrackerAutoLogin#1]
Can you add a config option to log to stderr instead of a log file? When running this on Unraid the Logs on the docker container are always blank because it is logging to the log file.

**Comment by mastiffmushroom** [comment]
Have some personal issues going on right now, should be able to implement this starting 3/20.

**Comment by halorrr** [comment]
No rush! Just documenting the issue for when you can get around to it (or for if I or anyone else wants to take a stab at it at some point).
