### ISSUE TITLE
[Feature Request] Tracker Addition - MTV

### ISSUE THREAD

**Issue by Soulplayer** [mastiffmushroom/TrackerAutoLogin#14]
LOGIN URL: https://www.morethantv.me/login
    POST LOGIN URL: https://www.morethantv.me/
    LOGIN TITLE: News :: MoreThanTV

**Comment by mastiffmushroom** [comment]
Added, please restart your docker container

**Comment by Soulplayer** [comment]
2023-04-03 08:25:38.501982 Attempting MoreThanTV
ERROR:root:2023-04-03 08:25:50.637334 : Failed to login to MoreThanTV due to Error: Message: 

WARNING:root:2023-04-03 08:25:50.689831 : Failed to login to MoreThanTV
