### ISSUE TITLE
[Feature Request] Tracker Addition - BLUTOPIA

### ISSUE THREAD

**Issue by Soulplayer** [mastiffmushroom/TrackerAutoLogin#15]
LOGIN URL: https://blutopia.xyz/login
POST LOGIN URL: https://blutopia.xyz/
LOGIN TITLE: Blutopia - Where Quality Matters

**Comment by mastiffmushroom** [comment]
Added, please restart your docker container

**Comment by Soulplayer** [comment]
2023-04-03 08:25:36.532041 Attempting Blutopia
ERROR:root:2023-04-03 08:25:38.448618 : Failed to login to Blutopia due to Error: 'password_box_type'
WARNING:root:2023-04-03 08:25:38.501897 : Failed to login to Blutopia
