### ISSUE TITLE
Running container causes the user_config.json to re-update

### ISSUE THREAD

**Issue by sorrento-lab** [mastiffmushroom/TrackerAutoLogin#16]
Hello,
I have a strange issue. If I create the configuration file as per my needs, say for example two trackers that are not Aither or Alpha Ratio (therefore they are deleted out), and then re-start the container, the user_config file will re-update itself to contain the first two sample trackers and my other two specified trackers. 
Specifying a legitimate login for Aither causes the user_config file to only update with Alpha Ratio sample login. 
Expected behaviour is for the user_config file to remain as the user specifies it. 
Currently it appears to be partly modified on container restart to always contain Aither or AlphaRatio (whether they are real logins or the sample ones).
Living your work @mastiffmushroom!

**Comment by mastiffmushroom** [comment]
It should not be doing this, but in thinking about how it initially runs, it makes sense that it‘s doing this. Going to have to think out a workaround while preserving the functionality

**Comment by digitalgp** [comment]
maybe autogenerate only if the config file is missing? its a bit anoying now as is :-)

**Comment by gardz** [comment]
@mastiffmushroom I love the idea of your project and I think I'll start helping add some features & fix some of these things up & send over some pull requests.

On this one, I wanted to check your thinking of auto updating the user_config.json file. I'm not sure this needs to be updated automatically / dynamically as it's always specific to the user? I understand the idea of updating the tracker_config.json file as it means new trackers can be added/updated without releasing a whole new version of TAL.

I think the fix here could be to have a sample user_config.json with an example commented out, that way the code behind this part can be cleaned up a bit. Before I went down the path of fixing up the logic for user_config.json I just wanted to double check your thinking on that one :-)

**Comment by mastiffmushroom** [comment]
I think the reason it's downloading the user_config is because I had it changing the first few iterations in the alpha release and I forgot to change it. I'm out of town for the next week or so, but I will try to make the fix after to where it will only download the user_config if it's not present.

**Comment by gardz** [comment]
I've proposed a fix to this plus a few other config file cleanup enhancements and extra error handling for missing files / malformed JSON files.

**Comment by mastiffmushroom** [comment]
Should be fixed thanks to @gardz and his pull request: https://github.com/mastiffmushroom/TrackerAutoLogin/pull/22

I've committed the changes to the main branch. 

Closing this issue
