### ISSUE TITLE
docker not starting

### ISSUE THREAD

**Issue by EvilUSB** [mastiffmushroom/TrackerAutoLogin#9]
I'm using unraid and docker.
Everything was working until yesterday. Today I needed to reinstall my dockers and I'm unable to start TrackerAutoLogin.
The error in the logs:

`Expecting ',' delimiter: line 75 column 5 (char 2883)`

There is a missing "," in trackerautologin/config/tracker_config.json
Even if I fix it, the docker is still unable to start. Same error and new file (temp_tracker_config.json) is created with the same missing ",".
It does not matter if I change the content of temp_tracker_config.json, as it is recreated again and again.

**Comment by mastiffmushroom** [comment]
You may have to delete your tracker_config.json file in /mnt/user/appdata/trackerautologin/config/ for it to work

**Comment by EvilUSB** [comment]
I can confirm - it works like a charm now.
Lightning fast reaction. Thanks!
